# Generated by Django 5.1.2 on 2024-11-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('submenu', models.ForeignKey(blank=True, help_text='If this menu item is a submenu, select its parent here. Leave blank if this is a top-level item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='BhimmaviApp.menus')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['-priority'],
            },
        ),
    ]
