# Generated by Django 5.1.2 on 2024-11-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('type', models.CharField(choices=[('General', 'General'), ('Event', 'Event'), ('Holiday', 'Holiday'), ('Urgent', 'Urgent')], default='General', max_length=10)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
