# Generated by Django 5.1.2 on 2024-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Competition', 'Competition'), ('Festival', 'Festival'), ('Others', 'Others')], default='Others', max_length=20)),
            ],
            options={
                'ordering': ['-event_date', '-event_time'],
            },
        ),
    ]
