# Generated by Django 5.1.2 on 2024-11-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni/')),
                ('detail', models.TextField()),
                ('slc_batch', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('current_position', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['slc_batch', 'name'],
            },
        ),
    ]
