# Generated by Django 5.1.2 on 2024-11-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0006_gallerytitle_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
    ]
