# Generated by Django 5.1.2 on 2024-11-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='written_by',
            field=models.CharField(max_length=100),
        ),
    ]
