# Generated by Django 5.1.2 on 2024-11-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0009_alter_blogpost_written_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentalumni',
            options={'ordering': ['-slc_batch']},
        ),
        migrations.RenameField(
            model_name='studentalumni',
            old_name='insta_link',
            new_name='twitter_link',
        ),
    ]
