# Generated by Django 5.1.2 on 2024-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0010_alter_studentalumni_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_link',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
