# Generated by Django 5.1.2 on 2024-11-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0018_teacher_created_at_teacher_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='board_members/images/')),
                ('title', models.CharField(max_length=50)),
                ('short_intro', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
