# Generated by Django 5.1.2 on 2024-11-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0020_bodmember_delete_boardmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('grade_applied_for', models.CharField(max_length=10)),
                ('academic_year', models.CharField(max_length=10)),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('last_academic_info', models.TextField()),
                ('co_curricular_activities', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
