# Generated by Django 5.1.2 on 2024-11-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0022_admission_deleted_at_admission_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodmember',
            name='experience',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
