# Generated by Django 5.1.2 on 2024-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0023_bodmember_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_text', models.TextField()),
                ('introduction_image1', models.ImageField(blank=True, null=True, upload_to='images/introduction/')),
                ('introduction_image2', models.ImageField(blank=True, null=True, upload_to='images/introduction/')),
                ('introduction_image3', models.ImageField(blank=True, null=True, upload_to='images/introduction/')),
                ('about_us_text', models.TextField()),
                ('about_us_image', models.ImageField(blank=True, null=True, upload_to='images/about_us/')),
                ('mission_text', models.TextField()),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='images/mission/')),
            ],
        ),
    ]
