# Generated by Django 5.1.2 on 2024-11-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0025_introduction_created_at_introduction_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='about_us_image',
            new_name='vision_image',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='about_us_text',
            new_name='vision_text',
        ),
    ]
