# Generated by Django 5.1.2 on 2024-11-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0026_rename_about_us_image_introduction_vision_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'verbose_name': 'Introduction', 'verbose_name_plural': 'Introduction'},
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='introduction',
            name='modified_at',
        ),
    ]
