# Generated by Django 5.1.2 on 2024-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0028_introduction_created_at_introduction_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introduction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Introduction', 'verbose_name_plural': 'Introduction'},
        ),
        migrations.AddField(
            model_name='introduction',
            name='introduction_home_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/introduction_home/'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='introduction_home_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/introduction_home/'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='no_of_awards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introduction',
            name='no_of_teacher',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introduction',
            name='student_each_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='introduction',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
