# Generated by Django 5.1.2 on 2024-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0029_alter_introduction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='no_of_awards',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='no_of_teacher',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='student_each_year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
