# Generated by Django 5.1.2 on 2024-11-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0030_alter_introduction_no_of_awards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodmember',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='introduction',
            name='student_each_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
