# Generated by Django 5.1.2 on 2024-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BhimmaviApp', '0032_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-history_year']},
        ),
        migrations.AlterField(
            model_name='history',
            name='history_year',
            field=models.DateField(),
        ),
    ]
